services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zhiyan
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DATABASE_URI: mysql+pymysql://root:root@mysql:3306/zhiyan
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "python -c 'from app import create_app; from extensions import db; app=create_app(); app.app_context().push(); db.create_all()' && flask run --host=0.0.0.0"


  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql_data:
