"""add pending_action

Revision ID: 6de03111c16e
Revises: 712b8a2c8ab1
Create Date: 2026-06-21 21:48:06.529169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de03111c16e'
down_revision = '712b8a2c8ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
