"""add token_count

Revision ID: ac1c2e3d3b07
Revises: 39895792c43f
Create Date: 2026-06-24 14:57:42.098795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1c2e3d3b07'
down_revision = '39895792c43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_call_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_call_log', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('token_count')

    # ### end Alembic commands ###
